//! See [llama-cpp-2](https://crates.io/crates/llama-cpp-2) for a documented and safe API.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(unpredictable_function_pointer_comparisons)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// Pre-norm embedding functions from `llama-ext.h`. Generated by a separate
// C++-mode bindgen pass so they carry the mangled `#[link_name]` matching their
// C++ linkage in libllama. Included after `bindings.rs` so their
// `*mut llama_context` parameters resolve to the type defined above.
include!(concat!(env!("OUT_DIR"), "/bindings_ext.rs"));
